apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tools
  source:
    repoURL: https://davidcharbonnier.github.io/deployments/
    targetRevision: 0.1.0
    chart: cert-manager
    helm:
      releaseName: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
    - CreateNamespace=true