apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tools
  source:
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.8.1
    chart: crossplane
    helm:
      releaseName: crossplane
      valueFiles:
      - https://raw.githubusercontent.com/davidcharbonnier/deployments/master/configurations/crossplane/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
    - CreateNamespace=true