apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynatrace
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tools
  source:
    repoURL: https://github.com/dynatrace-oss/dynatrace-gcp-function/tree/master/k8s/helm-chart
    targetRevision: 0.3.0
    chart: dynatrace-gcp-function
    helm:
      releaseName: dynatrace
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dynatrace
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
    - CreateNamespace=true