apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tools
  source:
    repoURL: hhttps://kubernetes.github.io/ingress-nginx
    targetRevision: 4.1.3
    chart: ingress-nginx
    helm:
      releaseName: ingress-nginx
      valueFiles:
      - https://raw.githubusercontent.com/davidcharbonnier/deployments/master/configurations/ingress-nginx/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
    - CreateNamespace=true